In [ ]:
A = ["aman","222",777,400.4]
print(type(A))
A = tuple(A)
print(A)
print(type(A))

<class 'list'>
('aman', '222', 777, 400.4)
<class 'tuple'>


In [2]:
#Q2
A = {"Roll_No":"CB.EN.U4CSE20262","Last_Name":"Suresh","First_Name":"Sreedath","DOB":"06/11/2002"}
print(A)
print(type(A))
print(A.keys())
print(A.values())

{'Roll_No': 'CB.EN.U4CSE20262', 'Last_Name': 'Suresh', 'First_Name': 'Sreedath', 'DOB': '06/11/2002'}
<class 'dict'>
dict_keys(['Roll_No', 'Last_Name', 'First_Name', 'DOB'])
dict_values(['CB.EN.U4CSE20262', 'Suresh', 'Sreedath', '06/11/2002'])


In [ ]:
#Q3
import numpy as np

np.random.seed()
print(np.random.rand(3,3))

[[0.45863878 0.94573277 0.73610214]
 [0.38765668 0.00536177 0.024435  ]
 [0.46044007 0.25996517 0.00133922]]


In [ ]:
#Q4
import numpy as np

print(np.random.uniform(0,1))
print(abs(-1234))

0.6879325249921001
1234


In [ ]:
#Q5
import numpy as np
def return_rand():
  return np.random.randint(20,90)

return_rand()

52

In [ ]:
#Q6
import numpy as np

A = [11,12,13,14,15]

print(A)
np.random.shuffle(A)
print("After Shuffling: ",A)


print(A[:3])

print(A[3])


[11, 12, 13, 14, 15]
After Shuffling:  [12, 13, 15, 14, 11]
[12, 13, 15]
14


In [ ]:
#Q7
F = open("King.txt","w")
F.write("The King is dead, Long Live the King")
F.close()

F = open("King.txt","r")
print(F.read())
F.close()

The King is dead, Long Live the King


In [ ]:
#Q8
def if_elif_else(n):
  if(n<0):
    print("Negative number!")
  elif(n>0):
    print("Positive number!")
  else:
    print("Zero!")

if_elif_else(10)
if_elif_else(-40)
if_elif_else(0)

Positive number!
Negative number!
Zero!


In [ ]:

def for_while(n):
  for i in range(n):
    print(n-i,end=" ")

  print()

  while(n>0):
    n-=1
    if(n==5):
      continue
    elif(n==2):
      break
    print(n,end=" ")
  
for_while(10)

10 9 8 7 6 5 4 3 2 1 
9 8 7 6 4 3 

In [ ]:
#Q9
A = "The King is dead, Long Live the King"

print(A)
print(A[0])
print(A[2:5])
print(A[2:])

print(A.split())
print(A.split("i"))

The King is dead, Long Live the King
T
e K
e King is dead, Long Live the King
['The', 'King', 'is', 'dead,', 'Long', 'Live', 'the', 'King']
['The K', 'ng ', 's dead, Long L', 've the K', 'ng']


In [ ]:
#Q10
import numpy as np

A = [1.0,4.0,5.0,8.0]
print(type(A))

A = np.array(list(map(int,A)))
print(type(A))

print(A[:2])

<class 'list'>
<class 'numpy.ndarray'>
[1 4]


In [ ]:
#Q11
import numpy as np

A = [1,2,3,4,5,6]

A = np.array(A)
A = A.reshape(2,3)
print(A)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Q12
import numpy as np

A = [1,2,3,4,5,6]

A = np.array(A)
A = A.reshape(2,3)

print(A[1])

print("[",end="")
for i in A:
  for j in i:
    print(j,end="., ")
print("]")

print(A.shape)
print(len(A))

[4 5 6]
[1., 2., 3., 4., 5., 6., ]
(2, 3)
2


In [ ]:
#Q13
import numpy as np

n = 10
A = np.array(np.arange(1,n+1))
print(A)

A = A.reshape(2,5)
print(A)

A = A.transpose()

print(A)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
#Q14
import numpy as np

A = [1,2,3]
A = np.array(A)

print(type(A))
print(A)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
#Q15
import numpy as np

A = [1,2,3]
A.append([9,9,9])
print(A)

[1, 2, 3, [9, 9, 9]]


In [ ]:
#Q16
A = [2,4,5]

sum = 0

for i in A:
  sum+=i

print(sum)

11


In [ ]:
#Q17
A = [77,74,75]

prod = 1

for i in A:
  prod*=i

print(prod)

427350


In [ ]:
#Q18
import numpy as np

A = [2,1,9,1,2,22,1,1,4,55,6,2,56]

print(np.mean(A))
print(np.var(A))
print(max(A))
print(min(A))
print(np.argmin(A))
print(A[(len(A)+1)//2])
print(np.argmax(A))
print(np.std(A))

12.461538461538462
367.32544378698225
56
1
1
1
12
19.165736192147232


In [ ]:
#Q19
import numpy as np

A = [1, 1, 4, 5, 5, 5, 7]

A = np.array(A)

B = np.unique(A)
print(A)
print(B)

np.sort(B)
print(B)

[1 1 4 5 5 5 7]
[1 4 5 7]
[1 4 5 7]


In [ ]:
#Q20
import numpy as np

A=[1,2,3]
B=[0,1,1]
print(np.dot(A,B))

5


In [ ]:
#Q21
import numpy as np

A = np.array([[2,-12],[1,-5]])
W,V = np.linalg.eig(A)
print(W)
print(V)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [1]:
#Q22
import numpy as np

A = [11, 22, 11, 31]
B = [25, 33, 31, 28]

print(np.corrcoef(A,B))

[[1.         0.15997968]
 [0.15997968 1.        ]]
