In [ ]:
import numpy as np

arr = np.array([1 ,2, 3, 4, 5])
print(arr)
print(arr.shape)
print(arr.ndim)

print("=====================================")

arr1 = np.array(42)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

print(type(arr))
print("=====================================")

arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

print("=====================================")

arr3 = np.array([[[1, 2, 3], [4, 5 ,6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

print("=====================================")

arr4 = np.array([1, 2, 3, 4], ndmin=5)

print(arr4)
print("number of dimensions :", arr4.ndim)
print(arr4.shape)

print("=====================================")

print('Slicing Arrays:')
print(arr1, arr[0], arr2[0][1], arr3[0][1][2])
print(arr1, arr[0], arr2[0, 1], arr3[0,1,2])
print(arr2)
print(arr2[-2, -1])

print("=====================================")

print('Slicing 1D Array:')
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[1:5])
print(arr4[-5:-1])
print(arr4[2:])
print(arr4[:4])
print(arr4[0:7:2])
print(arr4[::2])


print("=====================================")

print('Slicing 2D Array:')

ar5 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(ar5[1, 1:4])
print(ar5[0:2, 2])
print(ar5[0:2, 1:4])

print("=====================================")

print(ar5.dtype)

arr6 = np.array(['APPLE', 'banana', 'cherry'])
print(arr6.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)

print("Converting data type float to int:")
arr = np.array([3.47, 2.141, 4.15])
newarr = arr.astype('i')
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)


print("=====================================")
print("COPY:")
arr= np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

print("=====================================")
print("View:")
arr= np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)
x[0] = 125
print(arr)

print("=====================================")
print("Reshaping array 1D to 2D:")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

print("=====================================")
print("Reshaping array 1D to 3D:")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

print("=====================================")
print("Iterating arrays 1D:")
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

print("=====================================")
print("Iterating arrays 2D:")
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
for x in arr:
  for y in x:
    print(y)

print("=====================================")
print("Iterating arrays 3D:")
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

for x in arr:
  for y in x:
    for z in y:
      print(z)

      
print("=====================================")
print("Joining Numpy arrays:")

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print(arr.shape)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print(arr.shape)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
print(arr.shape)

print("=====================================")
print("Spliting NumPy arrays:")
arr = np.array([1, 2, 3, 4, 5, 6, 7])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

arr = np.array([[1, 2], [3, 4], [5, 6], [7,8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])

print("=====================================")
print("Searching arrays:")
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

x = np.where(arr%2 == 0)
print(x)

x = np.where(arr%2 == 1)
print(x)

print("=====================================")
print("Random NumPy:")

from numpy import random

x = random.randint(100)
print(x)

x1 = random.rand()
print(x1)

x2 = random.randint(100, size =(3, 5))
print(x2)

x3 = random.rand(3, 5)
print(x3)

print("=====================================")
print("Array Arithmethic:")

a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
b = np.array([[1, 0, 5], [2, 3, 7], [6, 4, 5]])

print(a+2)
print(a-1)
print(a*5)
print(a/2)

c = a + b
print(c)

d = a - b
print(d)

e = a*b
print(e)

print("=====================================")
print("Transpose of Arrays:")

a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
print(a)
ta = np.transpose(a)
print(ta)

print("=====================================")
print("Mean, Meridian, and Standard Deviation:")

a = np.arange(5,50,2)
print(a)
print('Mean : ', np.mean(a))
print('Standard Deviation : ', np.std(a))
print('Median : ', np.median(a))

print("=====================================")
print("Min and Max:")
print('Min : ', np.min(a))
print('Max : ', np.max(a))

a = np.array([[3, 2, 4], [10, 0 ,1], [7, 5, 8]])
print(a)
print('Min :', np.min(a, axis=0))
print('Max :', np.max(a, axis=1))

print("=====================================")
print("Random Distribution:")

from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

y = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(y)

print("=====================================")
print("Normal Distribution:")
x = random.normal(size=(2, 3))
print(x)

y = random.normal(loc=1, scale=2, size=(2, 3))
print(y)


[1 2 3 4 5]
(5,)
1
42
()
0
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)
Slicing Arrays:
42 1 2 6
42 1 2 6
[[1 2 3]
 [4 5 6]]
3
Slicing 1D Array:
[2 3 4 5]
[3 4 5 6]
[3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]
[1 3 5 7]
Slicing 2D Array:
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
Converting data type float to int:
[3.47  2.141 4.15 ]
float64
[3 2 4]
int32
[1.1 2.1 3.1]
float64
[1 2 3]
int64
COPY:
[42  2  3  4  5]
[1 2 3 4 5]
View:
[42  2  3  4  5]
[42  2  3  4  5]
[125   2   3   4   5]
Reshaping array 1D to 2D:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
Reshaping array 1D to 3D:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)
Iterating arrays 1D:
1
2
3
Iterating arrays 2D:
[1 2 3]
[4 5 6]
1
2
3
4
5
6
Iterating arrays 3D:
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 